line-length = 80
preview = false
exclude = [
    "**/migrations/",
    "task_manager/statuses/migrations/",
    "settings.py",
    ".venv/"
]

[lint]
select = ["E", "F", "I", "C90"]


[lint.per-file-ignores]
"__init__.py" = ["F401"]
